version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres_container_caso_de_uso

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: caso_de_uso
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
